idea:
    build: .
    labels:
        org.kurron.description: "JetBrains IntelliJ IDEA Java IDE"
        org.kurron.version: "15.0.1"
    container_name: "intellij"
    net: "host"
    volumes:
        - /tmp/.X11-unix:/tmp/.X11-unix
        - /home/vagrant:/home/developer
    environment:
        DISPLAY: unix:0.0
    user: 1000:1000
